#!/bin/bash
# determine if someone is logged on - Version 4
if [ "$#" -ne 1 ]
then      
	echo "Incorrect number of arguments"
	echo "Usage: on user"
else
	user="$1"

	if who | grep "^$user " > /dev/null
	then
		echo "$user is logged on"
	else 
		echo User not logged on.
	fi
fi
