#!/bin/bash
# rolo - rolodex program to look up, add, and
# remove people from the phone book
# Set PHONEBOOK to point to the phone book file
# and export it so other progs know about it

PHONEBOOK=$phonebook

export PHONEBOOK



if [ ! -f "$PHONEBOOK" ]

then

     echo "No phone book file in $HOME!"
     echo "Set your phonebook location when running. [Usage: phonebook=/your/path/phonebook rolo]"
     exit 1

fi



#

# If arguments are supplied, then do a lookup

#



if [ "$#" -ne 0 ]

then

     phonebook=$phonebook $HOME/Chapter11/lu "$@"

     exit

fi

validchoice=""         # set it null



#

# Loop until a valid selection is made

#



until [ -n "$validchoice" ]

do

     #

     # Display menu

     #



     echo '

     Would you like to:



     1. Look someone up

     2. Add someone to the phone book

     3. Remove someone from the phone book



Please select one of the above (1-3): \c'


# Read and process selection

#



read choice

echo



case "$choice"

in

      1) echo "Enter name to look up: \c"

         read name

         $HOME/Chapter11/lu "$name"

         validchoice=TRUE;;

      2) echo "Enter name to be added: \c"

         read name

         echo "Enter number: \c"

         read number

         add "$name" "$number"

         validchoice=TRUE;;

      3) echo "Enter name to be removed: \c"

         read name

         $HOME/Chapter11/rem "$name"

         validchoice=TRUE;;

      *) echo "Bad choice";;

     esac

done
