#!/bin/bash
# Wait until a specified user logs on or directory exists
# Set up default values
mailopt=FALSE
interval=60
# process command options
while getopts mft: option
do
     case "$option"
     in
            m) mailopt=TRUE;;
            f) directory=$directory;;
            t) interval=$OPTARG;;
           \?) echo "Usage: mon [-m] [-t n] user"
               echo "   -m means to be informed by mail"
               echo "   -t means check every n secs."
               exit 1;;
     esac
done
# Make sure a user name was specified
if [ "$OPTIND" -gt "$#" ]
then
     echo "Missing user name!"
     exit 2
fi
shiftcount=$((OPTIND -1))
shift $shiftcount
directory=$1
# Check for directory
until [ -d $directory ] > /dev/null
do
     sleep $interval
done
# When we reach this point, directory exists
if [ "$mailopt" = FALSE ]
then
     echo "$directory exists"
else
     runner=$(whoami)
echo "The $directory exists" | mail $runner
fi
user=$1
# Check for user logging on
until who | grep "^$user " > /dev/null
do
     sleep $interval
done
# When we reach this point, the user has logged on
if [ "$mailopt" = FALSE ]
then
     echo "$user has logged on"
else
     runner=$(whoami)
echo "$user has logged on" | mail $runner
fi
